harness/ff-nodejs-server-sdk

- .eslintrc.json
- example/index.js
- example/package-lock.json
- example/package.json
- package-lock.json
- package.json
- src/boolean.ts
- src/cache.ts
- src/constants.ts
- src/evaluator.ts
- src/index.ts
- src/json.ts
- src/log.ts
- src/number.ts
- src/polling.ts
- src/repository.ts
- src/store.ts
- src/streaming.ts
- src/string.ts
- src/types.ts
- src/utils.ts
Repository patternt with cache support
Flag rules evaluations
> [FFM-1263] flag rules evaluations, repository with persistent

- README.md
- Removed some inconsistent capitalisation 
- Fixed typos
> [fix]: [FFM-1935]: Fixed typos in NodeJS SDK README

- package.json
Installing `@harnessio/ff-nodejs-server-sdk` and importing it in a typescript project results in a typescript error[1]. The is caused by this package being built with `tsc --outfile` which is [not supposed to be used](https://www.typescriptlang.org/tsconfig/#outFile) with module files and should only be used for libraries which expose global variables. 
To reproduce the error, check out  [kdojeteri/harness-ff-typescript-error](https://github.com/kdojeteri/harness-ff-typescript-error).
This pull request removes the `--outfile ./dist/index.d.ts` parameter and replaces it with `--outdir ./dist`, which fixes the error.
[1]
```
$ tsc --noEmit
index.ts:1:32 - error TS2306: File '/Users/figure/Desktop/test/node_modules/@harnessio/ff-nodejs-server-sdk/dist/index.d.ts' is not a module.
1 import { …
```
> TypeScript: don't use outfile with tsc - it does not support modules

- package-lock.json
- package.json
This adds the jest-junit reporter.
We can use it to generate test results that will be reported through CI.
This requires a Junit style output
> (maint) Add support for JUnit output

- src/__tests__/client.test.ts
- src/client.ts
This PR ensures that the `pollInterval` and `eventSyncInterval` cannot be set lower than 60s.
Refs [FFM-3688](https://harness.atlassian.net/browse/FFM-3688)
> feat: [FFM-3688]: Ensure both pollInterval and eventSyncInterval adhere to a lower cap of 60s

- package.json
This PR changes the build target of the ESM build to use the `.mjs` suffix.
> fix: [FFM-3806]: Publish ESM as mjs

- src/evaluator.ts
The PR fixes an issue whereby evaluations of Target Group rules were not awaited properly, leading to the wrong variation being served.
Refs [FFM-4047](https://harness.atlassian.net/browse/FFM-4047)
> fix: [FFM-4047]: Ensure async calls are awaited

- README.md
- package.json
This PR replaces usage of `ngdocs` with `docs`.
> chore: [FFM-4083]: Update docs links

- package-lock.json
- package.json
- src/streaming.ts
- src/version.ts
This PR moves the call to fetch a Target Group/Flag into the create/patch condition to prevent it being called for delete events.
> fix: [FFM-4494]: Only fetch when create/edit

- examples/example/package-lock.json
- examples/getting_started/package-lock.json
- examples/getting_started/package.json
- package-lock.json
- package.json
- src/version.ts
Bump eventsource version in examples to 1.1.1 for dependebot Git CVE.
> FFM 4640 NodeJS Git CVE

- __tests__/evaluator.test.ts
- src/evaluator.ts
Update the test-cases submodule.
This pulls in over 70 new tests for the evaluator.
The evaluator test had to be updated to understand the newer format.  We also had to modify how the JSON results are confirmed.
> [FFM-5387]: Update Test Cases

- package-lock.json
- package.json
- src/streaming.ts
- src/version.ts
Adds functionality to abort the SSE stream if `Client.close()` is called. 
Manually called `close()` and the SSE connection aborts and does not retry connecting
> FFM-8116 Stop SSE when `Client.close()` is called

- package-lock.json
- package.json
- src/__tests__/sdk_codes.test.ts
- src/client.ts
- src/evaluator.ts
- src/metrics.ts
- src/polling.ts
- src/sdk_codes.ts
- src/streaming.ts
- src/version.ts
This PR focuses on three changes
1. If the SDK fails authentication, then the SDK will not attempt to start any services (which results in a crash) and will serve default variations to users. 
2. Adds a list of SDK codes we are rolling out across SDKs - see https://harness.atlassian.net/wiki/spaces/FFM/pages/21356052573/SDK+Codes 
3. We saw an issue reported by a customer that the `environment` claim was missing from the auth JWT. This adds some validation and logging for that rare scenario. 
Manual: 
1. SDK initialises and serves the expected flag variations 
2. SDK fails to initialise due to auth error or falsey API key and continues to to serve defaults
3. SDK Codes are logged correctly - I've included unit tests for these just to make sure all that code is tested.
4. Valid JWT claims …
> FFM-8289 Stop SDK crashing on auth failures / SDK Codes / JWT Validation

- src/__tests__/client.test.ts
There's an old test that is failing. Having looked at the code, it doesn't do what it's supposed to, so instead of adding a new test which asserts the client is closed I have opted to remove it. Have tested client is closed properly via manual testing
This test is failing in the `onTag` pipeline preventing a release. It passed in the build pipeline
> FFM-8323 Remove broken test for quick release

- README.md
- package-lock.json
- package.json
- src/client.ts
- src/version.ts
If authentication failed, the `Event.FAILED` event was not emitted and so the promise rejection was never handled by `waitForIntialization` , causing applications to exit with code 0 if the main script function is async
Happy path: awaitForInitialziation still waits
Sad path: Used local proxy which returns a `404` error. The promise rejection gets passed to the caller.
I've left a TODO comment over my change to get feedback on the approach we should take. Currently, this change means that the promise rejection will now be returned to the user, and it's up to them to handle it. But we could also just return the resolve promised, and allow the SDK to serve defaults. I think option A is better to give users more control.
> FFM-9055 Emit failed event if auth fails

- package-lock.json
- package.json
Because `lru-cache` is referenced in `ff-nodejs-server-sdk` definition file and "@types/lru-cache" is not deps
`tsc` will fail without setting `skipLibChecks` to true on the user side
or installing both `@types/lru-cache` and `lru-cache` on the user side
> fix: add type as deps

- package-lock.json
- package.json
- src/metrics.ts
- src/version.ts
[FFM-9621] - Avoid sending empty metric payloads
What
Adds a check to make sure metrics data is not empty before sending it.
Why
We're seeing empty metrics payloads arriving at the BE we should avoid wasting network bandwidth.
Testing
Manual
[FFM-9621]: https://harness.atlassian.net/browse/FFM-9621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-9621] - Avoid sending empty metric payloads

- package-lock.json
- package.json
- src/client.ts
- src/version.ts
Two log statements were using `console` instead of the `Logger` interface, this PR updates those references. 
So any customer loggers that are provides work across all log statements.
> FFM-9778 Update some log statements from console to the SDK's logger

- examples/getting_started/package-lock.json
- package-lock.json
- package.json
- src/__tests__/evaluator.test.ts
- src/__tests__/sdk_codes.test.ts
- src/evaluator.ts
- src/sdk_codes.ts
- src/version.ts
[FFM-10041] - Fall back to identifier if bucketBy attribute is not found
**What**
Update BucketBy logic to fall back to the target identifier if given BucketBy attribute is not found.
Adds new unit test to test fallback logic works.
**Why**
Keep the SDK consistent with the behaviour of the other server SDKs.
**Testing**
Testgrid + new unit test
[FFM-10041]: https://harness.atlassian.net/browse/FFM-10041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-10041] - Fall back to identifier if bucketBy attr is not found

- package-lock.json
- package.json
- src/version.ts
- tsconfig.json
This PR updates several dependencies and unbundles all dependencies. This PR also updates the target version of ECMAscript to match what was available in Node 12.
> feat: [FFM-10358]: Update and unbundle dependencies

- package-lock.json
- package.json
- src/client.ts
- src/version.ts
We allow targets to to undefined when calling variation methods, but if `"strictNullChecks": true` is enabled in a Typescript project, then passing an undefined target will result in a compilation fail.
This marks the `target` as explicitly optional for all variation methods.
Manual:
1. with project that enabled `strictNullChecks` and passed undefined targets and real targets with targeting rules enabled on each flag type.
2. with project with no `strictNullChecks` for undefined and real targets with targeting rules enabled on each flag type.
3. Metrics post for each of the above scenarios correctly.
> FFM-10409 Mark targets as optional for variation methods

- package-lock.json
- package.json
- src/evaluator.ts
- src/sdk_codes.ts
- src/version.ts
**What**
Fix prereq loop not to abort too soon, allowing subsequent prereqs to be processed
**Why**
The old logic aborts immediately after the first iteration of the loop. This causes a lot of test grid failures.
**Testing**
The following testgrid test cases are now working:
```
Custom_SDK_:_Type=BoolWith2JSON;State=Enabled;On=True;Off=False;Prereq=AlwaysOn;AlwaysOnToo;Return_False 
Custom_SDK_:_Type=BoolWith2Bool;State=Enabled;On=True;Off=False;Prereq=AlwaysOn;AlwaysOff;Return_False 
Custom_SDK_:_Type=BoolWith2Bool;State=Enabled;On=True;Off=False;Prereq=AlwaysOn;AlwaysOnToo;Return_False 
Custom_SDK_:_Type=BoolWithBoolJSON;State=Enabled;On=True;Off=False;Prereq=AlwaysOn;AlwaysOnToo;Return_False 
Custom_SDK_:_Type=JSONWith2Bool;State=Enabled;On=Com;Off=Val;Prereq=AlwaysOn;AlwaysOff;Return_V …
```
> [FFM-9291] - Fixed first prerequisite only being processed

- package-lock.json
- package.json
- src/client.ts
- src/streaming.ts
- src/version.ts
[FFM-7017] - Add Harness-SDK-Info/Harness-AccountID/Harness-EnvironmentID headers
**What**
Add meta data headers `Harness-SDK-Info`, `Harness-AccountID` and `Harness-EnvironmentID` to bring NodeJS in line with other server SDKs.
**Why**
Helps with backend load testing to identify problematic clients
**Testing**
Manual with Java SDK proxy
[FFM-7017]: https://harness.atlassian.net/browse/FFM-7017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FFM-7017] - Add Harness-SDK-Info/Harness-AccountID/Harness-EnvironmentID headers

- README.md
- src/client.ts
- src/metrics.ts
- src/streaming.ts
- src/types.ts
**What**
Adds a new option called `tlsTrustedCa` that takes a path to a file that contains a bundle of certificates in PEM format.
**Why**
Bring NodeJS into line with other SDKs by adding TLS support at the API level.
**Testing**
Tested with Java proxy (with TLS enabled) + testgrid
> [FFM-7017] - Add support for custom TLS CAs

- src/__tests__/sdk_codes.test.ts
- src/metrics.ts
- src/sdk_codes.ts
- Splits evaluation and target metrics into their own caches:
-  so that we can track target metrics correctly. Due to the fact we use the `globalTarget` , this meant that we would miss targets if the evaluation didn't change. 
- Implements limits: Evaluation metrics to 10K unique evaluations--where a unique evaluation is flag + variation--this allows for evaluation for 10k flags with 5 variations each
- Target metrics for 100K unique targets
- Implement seen targets:
- ensures that the metrics service only gets sent target metrics for a target once, for the lifetime of the SDK instance
- ensures that the SDK processes truly unique targets fairly, and that old targets don't occupy the 100K limit set per interval
- Metrics accuracy:
- TestGrid metrics tests
- Manual sample app
- …
> FFM-11022 Applies standard Metrics Enhancements

- api.yaml
- package-lock.json
- package.json
- src/__tests__/evaluator.test.ts
- src/evaluator.ts
- src/openapi/api.ts
[FFM-11243] - Target v2: Adding support for AND/OR in clauses
**What**
Adding support for processing the new `GroupServingRule` in `Segment`. Also update API definition for OpenAPIGenerator plugin. The default behaviour now is to check for the existence of `GroupServingRule` if found then we ignore the old `Rules` section. Old `Rules` section will continue to work to aid transition if `GroupServingRule` is not yet populated. Each entry in `GroupServingRule` is ORed while each list of clauses is ANDed. The `GroupServingRule` with the highest priority used first to allow reordering on the backend.
**Why**
This gives the customer more flexibility on how they configure their rules in the backend.
**Testing**
Initial unit tests for now + testgrid for existing rules
[FFM-11243]: …
> [FFM-11243] - Target v2: Adding support for AND/OR in clauses

- client-v1.yaml
- package.json
- src/client.ts
- src/constants.ts
- src/openapi/api.ts
- src/polling.ts
- src/streaming.ts
- src/types.ts
- Re-generates the API client to bring in the new target-segments query parameter rules
- Sets this parameter on the for requests to to `target-segments` (polling) and  `target-segments/{segment}` (streamed group changes)
Manual inspection of final URL string when
- Pulling all segments
- Pulling a specific segment when a group change has been streamed
> FFM-11364  Use target-segments v2-rule parameter

- package-lock.json
- package.json
- src/version.ts
STO scan failed on Braces CVE. This PR fixes it by running `npm audit fix` to patch the CVE
Manual - init/polling/streaming/metrics
> FFM-11673 Patch braces CVE

- package-lock.json
- package.json
- src/evaluator.ts
- src/repository.ts
- Move the group `AND/OR` rules outside of the critical evaluation path into the point we save them to the cache.
Avoid the cost of sorting multiple times during evaluations when it is unnecessary, which can add evaluation latency.
TestGrid - both old style and new style scenarios pass.
> FFM-11656 Sort Group Serving Rules rules when saving to cache

- package-lock.json
- package.json
- src/version.ts
Patches Axios CVE-2024-39338
Manual network requests:
- init
- streaming
- polling
- metrics
> FFM-11888 Patch Axios CVE: CVE-2024-39338

- package-lock.json
Patches CVE-2024-4067. This is found in `micromatch` which is used by dev dependencies only. No need to release this.
> FFM-11877 Dev Dependency patch: micromatch

- package-lock.json
- package.json
- src/__tests__/sdk_codes.test.ts
- src/client.ts
- src/evaluator.ts
- src/polling.ts
- src/sdk_codes.ts
- src/streaming.ts
- src/version.ts
Reduces log spam during stream connection issues by reducing frequency and level of logs depending on attempt #:
- Error log for `Issue with streaming: falling back to polling while the SDK attempts to reconnect`: Only show once per disconnect cycle
- Warning logs: Show on 1st, 10th, and every 50th retry attempt, with debug-level in between
- Combines disconnect and retry message in one log.
- Other reductions of logs which could become spammy. 
Verified in local environment with unstable connections that logs appear at expected thresholds and reconnection resets counters correctly.
> FFM-12353 Reduce excessive logs

- package-lock.json
- package.json
- src/client.ts
- src/constants.ts
- src/version.ts
SDK Auth currently does not retry and aborts instantly after 3 (rapid) attempts. This is because AxiosRetry is using default values and needs tuned.
- Updated the retry logic retry indefinitely instead of using default of 3
- Old exponential logic was not working correctly with default values. Instead configure exponential backoff logic with an upper delay limit of approximately 1 min. `axiosRetry.exponentialDelay` will also add a random delay of 20% to avoid retries hitting the BE server all at once across all deployed SDKs.
- Update the retry condition to catch more errors such as `ENOTFOUND` and `ECONNREFUSED` etc
***Testing***
Manual with an SDK proxy that can simulate network failures on the auth
> fix: [FFM_12484]: Node SDK doesn't retry after initialisation failure

- src/client.ts
When using the `tlsTrustedCa` option to the Client constructor, it has a private property called httpsCa that is never set. The Client constructor calls `createAxiosInstanceWithRetries`, to create the axios connection used by the PollingProcessor. The `createAxiosInstanceWithRetries` method of the Client class uses the argument `options.tlsTrustedCa` (containing the cert file path) passed to it to read the cert file and provides that to axios. However, the file is read into a local variable, `httpsCa`, *not* the Class property `httpsCa`. The class property `httpsCa` is never set. When the StreamProcessor is created by the Client, one of it's arguments is `this.httpsCa`, which is never set and thus the StreamProcessor never has access to the cert.
When the `baseUrl` and `eventsUrl` are …
> Provide tlsTrustedCa/httpsCa to StreamProcessor
